version: "3.8"

services:
  db:
    image: postgres:15
    container_name: database_backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${SCHEMA}

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
